language: groovy

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
 - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8

script:
 - ./gradlew check